# Altyapı
FROM node:current-alpine3.20

# Çalışma Alanı
WORKDIR /app

# Dosyaları Aktar

# COPY hello.js /app // tek dosya seçme

COPY . .

# Komut Çalıştır
# CMD node hello.js // tavsiye edilmiyor

CMD ["node", "hello.js"]